import localFont from "next/font/local";
import { Rubik_Wet_Paint, Trocchi } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const rubikWetPaint = Rubik_Wet_Paint({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik-wet-paint",
});

const trocchi = Trocchi({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-trocchi",
});

export const metadata = {
  title: "Game Of Thrones",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubikWetPaint.variable} ${trocchi.variable} antialiased`}
      >
        <main>
          <Navbar/>
          {children}
          <Footer/>
        </main>
        
      </body>
    </html>
  );
}
